# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key

-   repo: https://github.com/gitguardian/ggshield
    rev: v1.29.0
    hooks:
    -   id: ggshield
        language_version: python3
        stages: [commit]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
    -   id: gitleaks

-   repo: https://github.com/thoughtworks/talisman
    rev: 'v1.32.0'  # Update me!
    hooks:
    # both pre-commit and pre-push supported
    # -   id: talisman-push
    -   id: talisman-commit
        entry: cmd --githook pre-commit
